name: Gradle wrapper test

on:
  pull_request:
    paths:
      - gradle/wrapper
  push:
    paths:
      - gradle/wrapper

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run new gradle wrapper
        uses: gradle/gradle-build-action@v1
        with:
          gradle-version: wrapper